with CTE AS(
    SELECT 
    TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
    CASE
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('sat','sun')
    then 'WEEKEND'
    else 'WEEKDAY'
    END AS DAY_TYPE,

    CASE
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (11,12,1,2)
    THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5,6)
    THEN 'SUMMER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (7,8,9)
    THEN 'RAINY'
    ELSE 'AUTAMN'
    END AS STARTED_AT_SEASONS
    
    
    FROM {{ source('DEMO', 'BIKE') }} WHERE STARTED_AT!='stoptime'
)
SELECT * FROM CTE