with TRIPS AS(
    SELECT 
    RIDE_ID,
    DATE(TO_TIMESTAMP(RIDEABLE_TYPE)) AS TRIP_DATE,
    ENDED_AT AS START_STATION_ID,
    END_STATION_ID,
    MEMBER_CSUAL AS MEMBER_CASUAL,
    TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(RIDEABLE_TYPE),TO_TIMESTAMP(STARTED_AT)) AS TRIP_DURATION_SECONDS

    from {{ source('DEMO', 'BIKE') }}
    WHERE RIDE_ID!='tripduration'

)

SELECT * FROM TRIPS