{%macro function1(x)%}
CASE 
WHEN TO_TIMESTAMP({{x}})< CURRENT_DATE 
THEN 'PAST'
ELSE 'FUTURE'
END AS PAST_OR_FUTURE,

CASE 
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (11,12,1,2)
THEN 'WINTER'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (3,4,5,6)
THEN 'SUMMER'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (7,8,9)
THEN 'RAINY'
ELSE 'AUTAMN'
END AS START_SEASON,

CASE
    WHEN DAYNAME(TO_TIMESTAMP({{x}})) IN ('sat','sun')
    then 'WEEKEND'
    else 'WEEKDAY'
    END AS DAY_TYPE,

{%endmacro%}
